# Generated by Django 4.2.7 on 2024-01-28 05:19

import coreApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0004_vendor_date_alter_product_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='cover_image',
            field=models.ImageField(default='vendor.jpg', upload_to=coreApp.models.user_directory_path),
        ),
    ]
